//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LADLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LAActivityEntities : DbContext
    {
        public LAActivityEntities()
            : base("name=LAActivityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityType> ActivityType { get; set; }
        public virtual DbSet<LearningActivity> LearningActivity { get; set; }
        public virtual DbSet<LearningObject> LearningObject { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Works> Works { get; set; }
        public virtual DbSet<WorksFile> WorksFile { get; set; }
        public virtual DbSet<ActionTotalDuring> ActionTotalDuring { get; set; }
        public virtual DbSet<CountLocation> CountLocation { get; set; }
        public virtual DbSet<CountTypes> CountTypes { get; set; }
        public virtual DbSet<CovertStartToDay> CovertStartToDay { get; set; }
        public virtual DbSet<laCountsbyUser> laCountsbyUser { get; set; }
        public virtual DbSet<LocationTotalDuring> LocationTotalDuring { get; set; }
        public virtual DbSet<QuerylearningActivity> QuerylearningActivity { get; set; }
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual ObjectResult<la_GetLongestActionsByUserID_Result> la_GetLongestActionsByUserID(Nullable<long> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<la_GetLongestActionsByUserID_Result>("la_GetLongestActionsByUserID", uidParameter);
        }
    
        public virtual ObjectResult<la_GetLongestActionsByUserIdBetweenTimeSpan_Result> la_GetLongestActionsByUserIdBetweenTimeSpan(Nullable<long> userId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<la_GetLongestActionsByUserIdBetweenTimeSpan_Result>("la_GetLongestActionsByUserIdBetweenTimeSpan", userIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<la_GetLongestLocationsByUserId_Result> la_GetLongestLocationsByUserId(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<la_GetLongestLocationsByUserId_Result>("la_GetLongestLocationsByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<la_GetMostLocationsByUserId_Result> la_GetMostLocationsByUserId(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<la_GetMostLocationsByUserId_Result>("la_GetMostLocationsByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<la_GetMostTypesByUserId_Result> la_GetMostTypesByUserId(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<la_GetMostTypesByUserId_Result>("la_GetMostTypesByUserId", userIdParameter);
        }
    }
}
