//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LADLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuerylearningActivity
    {
        public Nullable<System.DateTime> 开始时间 { get; set; }
        public string 开始日期 { get; set; }
        public string 开始时间点 { get; set; }
        public Nullable<int> 持续时长 { get; set; }
        public string 作品地址 { get; set; }
        public string 活动描述 { get; set; }
        public string 活动类型 { get; set; }
        public string 学习对象 { get; set; }
        public string 对象描述 { get; set; }
        public string 学习内容 { get; set; }
        public string 活动地点 { get; set; }
        public long UserID { get; set; }
        public long LearningActivityID { get; set; }
        public Nullable<System.DateTime> 创建时间 { get; set; }
        public Nullable<System.DateTime> 修改时间 { get; set; }
        public long LocationID { get; set; }
        public long ActivityTypeID { get; set; }
    }
}
