//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestDll
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContestEntities : DbContext
    {
        public ContestEntities()
            : base("name=ContestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Career> Career { get; set; }
        public virtual DbSet<College> College { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Degree> Degree { get; set; }
        public virtual DbSet<ExpertGroupType> ExpertGroupType { get; set; }
        public virtual DbSet<ExpertWorksType> ExpertWorksType { get; set; }
        public virtual DbSet<Periods> Periods { get; set; }
        public virtual DbSet<PeriodStandard> PeriodStandard { get; set; }
        public virtual DbSet<RatingDetails> RatingDetails { get; set; }
        public virtual DbSet<ResetPassword> ResetPassword { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<ScoreStandard> ScoreStandard { get; set; }
        public virtual DbSet<Specialty> Specialty { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserWorks> UserWorks { get; set; }
        public virtual DbSet<Works> Works { get; set; }
        public virtual DbSet<WorksComments> WorksComments { get; set; }
        public virtual DbSet<WorksExpert> WorksExpert { get; set; }
        public virtual DbSet<WorksFile> WorksFile { get; set; }
        public virtual DbSet<WorksType> WorksType { get; set; }
        public virtual DbSet<WorksTypeScoreStandard> WorksTypeScoreStandard { get; set; }
        public virtual DbSet<UserState> UserState { get; set; }
        public virtual DbSet<CSPeriodScoreStandard> CSPeriodScoreStandard { get; set; }
        public virtual DbSet<CSPeriodsCourse> CSPeriodsCourse { get; set; }
        public virtual DbSet<CSPeriodsWorksType> CSPeriodsWorksType { get; set; }
        public virtual DbSet<CSUserWorks> CSUserWorks { get; set; }
        public virtual DbSet<CSWorksExpertUser> CSWorksExpertUser { get; set; }
        public virtual DbSet<CSWorksToEvaluate> CSWorksToEvaluate { get; set; }
        public virtual DbSet<CSWorksTypeScoreStandard> CSWorksTypeScoreStandard { get; set; }
        public virtual DbSet<CSWorksWorksType> CSWorksWorksType { get; set; }
        public virtual DbSet<CSMyWorks> CSMyWorks { get; set; }
        public virtual DbSet<CSWorksPublic> CSWorksPublic { get; set; }
        public virtual DbSet<CSVWorksForMe> CSVWorksForMe { get; set; }
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<CSVUserSocre> CSVUserSocre { get; set; }
        public virtual DbSet<FinalsScoreStandard> FinalsScoreStandard { get; set; }
        public virtual DbSet<CSFinalsExpertGroup> CSFinalsExpertGroup { get; set; }
        public virtual DbSet<CSFinalsExpertWillScore> CSFinalsExpertWillScore { get; set; }
        public virtual DbSet<CSExpertWorksTypeDetail> CSExpertWorksTypeDetail { get; set; }
        public virtual DbSet<CSWorksPartition> CSWorksPartition { get; set; }
        public virtual DbSet<CSSchoolWorksNum> CSSchoolWorksNum { get; set; }
        public virtual DbSet<CSUserWithSchoolAndRole> CSUserWithSchoolAndRole { get; set; }
    }
}
