//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSExpertWorksTypeDetail
    {
        public string WorksTypeName { get; set; }
        public int WorksTypeID { get; set; }
        public Nullable<long> Flag { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public Nullable<int> ParentID { get; set; }
        public long ExpertWorksTypeID { get; set; }
        public long UserRoleID { get; set; }
        public long UserID { get; set; }
        public int RoleID { get; set; }
    }
}
