//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPeriodsCourse
    {
        public long PeriodID { get; set; }
        public string PeriodTitle { get; set; }
        public Nullable<int> WorksCount { get; set; }
        public string CourseName { get; set; }
        public Nullable<System.DateTime> StartSubmit { get; set; }
        public Nullable<System.DateTime> EndSubmit { get; set; }
        public Nullable<System.DateTime> StartScore { get; set; }
        public Nullable<System.DateTime> EndScore { get; set; }
        public Nullable<System.DateTime> StartPublic { get; set; }
        public Nullable<System.DateTime> EndPublic { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> CourseID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> WorksTypeID { get; set; }
        public string WorksTypeName { get; set; }
        public Nullable<int> Number { get; set; }
        public string Require { get; set; }
        public string PeriodCode { get; set; }
    }
}
