//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSVUserSocre
    {
        public string PeriodTitle { get; set; }
        public string CourseName { get; set; }
        public string Account { get; set; }
        public long UserID { get; set; }
        public string Name { get; set; }
        public Nullable<float> Score { get; set; }
        public string WorksName { get; set; }
        public string SchoolName { get; set; }
        public Nullable<long> CourseID { get; set; }
        public long PeriodID { get; set; }
        public long WorksID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> WorksState { get; set; }
        public Nullable<int> Relationship { get; set; }
    }
}
