//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSVWorksForMe
    {
        public Nullable<long> ExpertID { get; set; }
        public Nullable<long> WorksID { get; set; }
        public Nullable<float> Score { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ScoreState { get; set; }
        public Nullable<long> Flag { get; set; }
        public long WorksExpertID { get; set; }
        public Nullable<long> PeriodID { get; set; }
    }
}
