//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSWorksWorksType
    {
        public long WorksID { get; set; }
        public Nullable<long> PeriodID { get; set; }
        public string WorksName { get; set; }
        public string TeamName { get; set; }
        public string WorksCode { get; set; }
        public Nullable<int> OrgID { get; set; }
        public Nullable<int> IsSample { get; set; }
        public string Comment { get; set; }
        public string Profile { get; set; }
        public Nullable<long> Flag { get; set; }
        public Nullable<int> WorksState { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<float> Score { get; set; }
        public string BackReason { get; set; }
        public string DemoURL { get; set; }
        public string SelfAssessment { get; set; }
        public string KeyPoints { get; set; }
        public string SubmitProfile { get; set; }
        public string Suggestion { get; set; }
        public string InstallationGuide { get; set; }
        public string DesignIdeas { get; set; }
        public string WorksTypeName { get; set; }
        public Nullable<int> WorksTypeID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
