//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestDll
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class CSWorksPublic
    {
        public string WorksName { get; set; }
        public Nullable<int> WorksTypeID { get; set; }
        public double ExpertScore { get; set; }
        public double TSScore { get; set; }
        public string WorksTypeName { get; set; }
        public Nullable<long> PeriodID { get; set; }
        public long WorksID { get; set; }
        public string WorksCode { get; set; }
    }
}
