//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodStandard
    {
        public int WorkTypeID { get; set; }
        public long PeriodID { get; set; }
        public int StandardID { get; set; }
        public string StandardDescription { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<int> Flag { get; set; }
    
        public virtual Periods Periods { get; set; }
        public virtual ScoreStandard ScoreStandard { get; set; }
        public virtual WorksType WorksType { get; set; }
    }
}
