//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestDll
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Periods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Periods()
        {
            this.PeriodStandard = new HashSet<PeriodStandard>();
            this.Works = new HashSet<Works>();
        }
    
        public long PeriodID { get; set; }
        public string PeriodTitle { get; set; }
        public Nullable<long> CourseID { get; set; }
        public string Require { get; set; }
        public Nullable<int> WorksTypeID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> StartSubmit { get; set; }
        public Nullable<System.DateTime> EndSubmit { get; set; }
        public Nullable<System.DateTime> StartScore { get; set; }
        public Nullable<System.DateTime> EndScore { get; set; }
        public Nullable<System.DateTime> StartPublic { get; set; }
        public Nullable<System.DateTime> EndPublic { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> Flag { get; set; }
        public string PeriodCode { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodStandard> PeriodStandard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Works> Works { get; set; }
    }
}
