//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public long UserRoleID { get; set; }
        public long UserID { get; set; }
        public int RoleID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<long> ContestID { get; set; }
        public Nullable<long> Flag { get; set; }
    }
}
