//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_ToExpertProj
    {
        public long ProjectID { get; set; }
        public string PName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<long> Sponsor { get; set; }
        public long UserID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
    }
}
