//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_Comments
    {
        public long CommentID { get; set; }
        public Nullable<int> Stars { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<int> CType { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<long> ItemID { get; set; }
    }
}
