//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_VUserScore
    {
        public long UserID { get; set; }
        public long ProjectID { get; set; }
        public string PName { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<double> PScore { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string SchoolName { get; set; }
        public long MemberID { get; set; }
        public string Account { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ApplyInTime { get; set; }
        public string StateName { get; set; }
    }
}
