//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proj_Project()
        {
            this.Proj_ExpertProjects = new HashSet<Proj_ExpertProjects>();
            this.Proj_ProjectApprove = new HashSet<Proj_ProjectApprove>();
            this.proj_ProjectFile = new HashSet<proj_ProjectFile>();
            this.Proj_Match = new HashSet<Proj_Match>();
            this.Proj_Member = new HashSet<Proj_Member>();
        }
    
        public long ProjectID { get; set; }
        public string PName { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<long> Sponsor { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> TypeID { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public string Introduce { get; set; }
        public string Background { get; set; }
        public string Implementation { get; set; }
        public string ExpectedGoal { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string PCode { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> IsMatch { get; set; }
        public Nullable<double> PScore { get; set; }
    
        public virtual Proj_State Proj_State { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proj_ExpertProjects> Proj_ExpertProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proj_ProjectApprove> Proj_ProjectApprove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proj_ProjectFile> proj_ProjectFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proj_Match> Proj_Match { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proj_Member> Proj_Member { get; set; }
    }
}
