//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_UserProject
    {
        public Nullable<long> MemberID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<System.DateTime> ApplyInTime { get; set; }
        public string ApprovedInTime { get; set; }
        public Nullable<long> ApprovedInBy { get; set; }
        public Nullable<System.DateTime> ApplyOutTime { get; set; }
        public string OutReason { get; set; }
        public Nullable<System.DateTime> ApprovedOutTime { get; set; }
        public Nullable<long> ApprovedOutBy { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> Flag { get; set; }
        public string PName { get; set; }
        public string PCode { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<long> Sponsor { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> TypeID { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public string Introduce { get; set; }
        public string Background { get; set; }
        public string Implementation { get; set; }
        public string ExpectedGoal { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public long ProjProjectID { get; set; }
        public Nullable<int> ProjectFlag { get; set; }
    }
}
