//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_VExpert
    {
        public long UserID { get; set; }
        public string Account { get; set; }
        public string Name { get; set; }
        public string IDCard { get; set; }
        public string Telephone { get; set; }
        public string Duty { get; set; }
        public string ProfessionalTitle { get; set; }
        public string Department { get; set; }
        public string Major { get; set; }
        public string Class { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string Grade { get; set; }
        public string RoleName { get; set; }
        public string Email { get; set; }
        public string Sex { get; set; }
        public string SchoolName { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> RoleID { get; set; }
    }
}
