//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDll
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
        public ProjectEntities()
            : base("name=ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Proj_Project> Proj_Project { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Career> Career { get; set; }
        public virtual DbSet<Degree> Degree { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<Proj_State> Proj_State { get; set; }
        public virtual DbSet<Proj_ProjectState> Proj_ProjectState { get; set; }
        public virtual DbSet<Proj_UserProject> Proj_UserProject { get; set; }
        public virtual DbSet<Proj_ProjectApprove> Proj_ProjectApprove { get; set; }
        public virtual DbSet<Proj_ProjectsCreatedByUser> Proj_ProjectsCreatedByUser { get; set; }
        public virtual DbSet<Proj_ProjectsIAmINorOut> Proj_ProjectsIAmINorOut { get; set; }
        public virtual DbSet<proj_ProjectFile> proj_ProjectFile { get; set; }
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<Proj_Match> Proj_Match { get; set; }
        public virtual DbSet<Proj_ExpertProjects> Proj_ExpertProjects { get; set; }
        public virtual DbSet<Proj_ToExpertProj> Proj_ToExpertProj { get; set; }
        public virtual DbSet<Proj_VExpert> Proj_VExpert { get; set; }
        public virtual DbSet<Proj_MatchResult> Proj_MatchResult { get; set; }
        public virtual DbSet<Proj_CountProjMember> Proj_CountProjMember { get; set; }
        public virtual DbSet<Proj_VUserWithRole> Proj_VUserWithRole { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Proj_VUserRoles> Proj_VUserRoles { get; set; }
        public virtual DbSet<Proj_Member> Proj_Member { get; set; }
        public virtual DbSet<Proj_VUserScore> Proj_VUserScore { get; set; }
        public virtual DbSet<Proj_Comments> Proj_Comments { get; set; }
    }
}
