//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_Member
    {
        public long MemberID { get; set; }
        public long UserID { get; set; }
        public long ProjectID { get; set; }
        public Nullable<System.DateTime> ApplyInTime { get; set; }
        public string ApprovedInTime { get; set; }
        public Nullable<long> ApprovedInBy { get; set; }
        public Nullable<System.DateTime> ApplyOutTime { get; set; }
        public string OutReason { get; set; }
        public Nullable<System.DateTime> ApprovedOutTime { get; set; }
        public Nullable<long> ApprovedOutBy { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> Flag { get; set; }
    
        public virtual Proj_Project Proj_Project { get; set; }
        public virtual User User { get; set; }
    }
}
