//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_VUserRoles
    {
        public string RoleName { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public int RoleID { get; set; }
        public long UserID { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<long> Flag { get; set; }
        public Nullable<int> SystemID { get; set; }
        public string Account { get; set; }
        public string Name { get; set; }
        public long UserRoleID { get; set; }
    }
}
